# SQLite Datasource Configuration
spring.datasource.url=jdbc:sqlite:${DB_FILE:dev_construction.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Desactivar Flyway en DEV si Hibernate maneja el schema (update)
spring.flyway.enabled=false

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
