CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    amount NUMERIC(15, 2) NOT NULL CHECK (amount >= 0),
    currency CHAR(3) NOT NULL CHECK (currency = UPPER(currency)),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE evidence ALTER COLUMN phase_id DROP NOT NULL;
ALTER TABLE evidence ADD COLUMN expense_id BIGINT REFERENCES expenses(id);
ALTER TABLE evidence ADD CONSTRAINT evidence_exactly_one_target
    CHECK ((phase_id IS NOT NULL AND expense_id IS NULL)
        OR (phase_id IS NULL AND expense_id IS NOT NULL));

CREATE INDEX idx_expenses_project_id ON expenses(project_id);
CREATE INDEX idx_evidence_expense_id ON evidence(expense_id);
