CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL UNIQUE REFERENCES projects(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'APPROVED', 'CLOSED')),
    currency CHAR(3) NOT NULL CHECK (currency = UPPER(currency)),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE budget_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL REFERENCES budgets(id),
    phase_id BIGINT REFERENCES project_phases(id),
    description VARCHAR(200) NOT NULL,
    category VARCHAR(100),
    unit VARCHAR(50),
    planned_quantity NUMERIC(15, 3) NOT NULL CHECK (planned_quantity > 0),
    unit_price NUMERIC(15, 2) NOT NULL CHECK (unit_price >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE expenses ADD COLUMN budget_id BIGINT REFERENCES budgets(id);
ALTER TABLE expenses ADD COLUMN budget_item_id BIGINT REFERENCES budget_items(id);
ALTER TABLE expenses ADD COLUMN description VARCHAR(500);

CREATE INDEX idx_budget_items_budget_id ON budget_items(budget_id);
CREATE INDEX idx_expenses_budget_id ON expenses(budget_id);
CREATE INDEX idx_expenses_budget_item_id ON expenses(budget_item_id);
