CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(30) NOT NULL CHECK (category IN ('MATERIAL', 'TOOL', 'EQUIPMENT', 'OFFICE_SUPPLY')),
    unit VARCHAR(30) NOT NULL,
    tracking_mode VARCHAR(20) NOT NULL CHECK (tracking_mode IN ('QUANTITY', 'SERIALIZED')),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE inventory_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('WAREHOUSE', 'PROJECT_SITE')),
    project_id BIGINT REFERENCES projects(id),
    address VARCHAR(500),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_inventory_location_project CHECK (
        (type = 'WAREHOUSE' AND project_id IS NULL)
        OR (type = 'PROJECT_SITE' AND project_id IS NOT NULL)
    )
);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL CHECK (type IN ('RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT', 'RETURN')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'POSTED')),
    source_location_id BIGINT REFERENCES inventory_locations(id),
    target_location_id BIGINT REFERENCES inventory_locations(id),
    adjustment_direction VARCHAR(20) CHECK (adjustment_direction IN ('INCREASE', 'DECREASE')),
    reversal_of_id BIGINT UNIQUE REFERENCES inventory_movements(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_inventory_movement_direction CHECK (
        (type = 'RECEIPT' AND source_location_id IS NULL AND target_location_id IS NOT NULL AND adjustment_direction IS NULL)
        OR (type IN ('ISSUE', 'RETURN') AND source_location_id IS NOT NULL AND target_location_id IS NULL AND adjustment_direction IS NULL)
        OR (type = 'TRANSFER' AND source_location_id IS NOT NULL AND target_location_id IS NOT NULL AND source_location_id <> target_location_id AND adjustment_direction IS NULL)
        OR (type = 'ADJUSTMENT' AND source_location_id IS NOT NULL AND target_location_id IS NULL AND adjustment_direction IS NOT NULL)
    )
);

CREATE TABLE inventory_movement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id BIGINT NOT NULL REFERENCES inventory_movements(id),
    item_id BIGINT NOT NULL REFERENCES inventory_items(id),
    quantity NUMERIC(15,3) NOT NULL CHECK (quantity > 0),
    serial_number VARCHAR(150),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_inventory_lines_item ON inventory_movement_lines(item_id);
CREATE INDEX idx_inventory_lines_movement ON inventory_movement_lines(movement_id);
CREATE INDEX idx_inventory_movements_status ON inventory_movements(status);
CREATE INDEX idx_inventory_movements_source ON inventory_movements(source_location_id);
CREATE INDEX idx_inventory_movements_target ON inventory_movements(target_location_id);
CREATE INDEX idx_inventory_locations_project ON inventory_locations(project_id);
CREATE INDEX idx_inventory_movements_reversal ON inventory_movements(reversal_of_id);
ALTER TABLE inventory_movement_lines ADD CONSTRAINT ck_inventory_line_serial_not_blank CHECK (
    serial_number IS NULL OR length(trim(serial_number)) > 0
);
