CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(30) NOT NULL CHECK (type IN ('INVITATION')),
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    resource_type VARCHAR(50),
    resource_id BIGINT,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notifications_recipient_id ON notifications(recipient_user_id);
CREATE INDEX idx_notifications_recipient_read_at ON notifications(recipient_user_id, read_at);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);
