package io.github.alexisTrejo11.construction.company.shared.authorization;

public enum Permission {
    USER_INVITE,
    USER_READ,
    USER_UPDATE,
    USER_ROLE_MANAGE,
    USER_STATUS_MANAGE,
    PROJECT_CREATE,
    PROJECT_READ,
    PROJECT_UPDATE,
    PROJECT_CHANGE_STATUS,
    PROJECT_RESTORE,
    PROJECT_GLOBAL_SUMMARY,
    PHASE_CREATE,
    PHASE_READ,
    PHASE_UPDATE,
    PHASE_CHANGE_STATUS,
    PHASE_REORDER,
    MEMBER_MANAGE,
    MEMBER_READ,
    EVIDENCE_CREATE,
    EVIDENCE_READ,
    EVIDENCE_UPDATE,
    EVIDENCE_DELETE,
    ATTACHMENT_CREATE,
    ATTACHMENT_READ,
    ATTACHMENT_DELETE
    ,BUDGET_CREATE, BUDGET_READ, BUDGET_UPDATE, BUDGET_APPROVE, BUDGET_REVISE, BUDGET_CLOSE
    ,BUDGET_ITEM_CREATE, BUDGET_ITEM_READ, BUDGET_ITEM_UPDATE, BUDGET_ITEM_DELETE
    ,EXPENSE_CREATE, EXPENSE_READ, EXPENSE_UPDATE, EXPENSE_SUBMIT, EXPENSE_APPROVE
    ,EXPENSE_REJECT, EXPENSE_CORRECT
}
